### ISSUE TITLE
NameError: name 'warn_led' isn't defined in line 55

### ISSUE THREAD

**Issue by frederik042853** [pimoroni/enviro#36] opened 2022-08-28 22:48 UTC
When I run the Main.py in Thonny I get this error:
2000-01-01 01:01:26 [debug    /   98096] > performing startup
2000-01-01 01:01:26 [debug    /   96400]   - hold vsys_en high
2000-01-01 01:01:26 [info     /  126400]   - wake reason: unknown
2000-01-01 01:01:26 [debug    /  124672]   - turn on activity led
2000-01-01 01:01:26 [info     /  120624] > clock not set, synchronise from ntp server
2000-01-01 01:01:26 [info     /  105712] > connecting to wifi network 'Vermeer'
2000-01-01 01:01:30 [error    /  127328] ! failed to connect to wireless network Vermeer
2000-01-01 01:01:30 [error    /  125376] ! failed to synchronise clock
Traceback (most recent call last):
  File "<stdin>", line 55, in <module>
NameError: name 'warn_led' isn't defined

Could use some help in resolving

**Comment by lowfatcode** [comment] 2022-08-30 07:13
Apologies, this was caused by a rearrange of the structure of the firmware - it should be fixed in https://github.com/pimoroni/enviro/commit/f078ee1658c8c908b29fe53f16b3b967ccb46213

**Closed** 2022-08-30 07:13 UTC
